using Presentation.WebApp.Models;

namespace Presentation.WebApp.Services;

// Generated by ChatGPT

public class ProductService
{
    private readonly List<Product> _products;

    public ProductService(List<Product> products)
    {
        _products = products ?? new List<Product>();
    }

    public Task<IEnumerable<Product>> GetProducts()
    {
        return Task.FromResult<IEnumerable<Product>>(_products);
    }
}